spring.datasource.url=jdbc:postgresql://localhost:5432/church
spring.datasource.username=church
spring.datasource.password=church
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.enabled=false

spring.mail.host=smtp.gmail.com
spring.mail.port=exemplo
spring.mail.username=exemplo
spring.mail.password=exemplo

app.mail.from=exemplo

security.jwt.secret-key=exemplo
security.jwt.expiration-time=86400000